### ISSUE TITLE
Try using "learning to rank" with Elasticsearch duplicate detection

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1275]

**Comment by ayush-1506** [comment]
@marco-c I'm looking at how learning to rank works and the first step is creating a judgement list: something that gives an idea of how similar two queries are, similar to labels for our data. (This is useful in the later training stage) [here](https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/core-concepts.html#judgments-expression-of-the-ideal-ordering). In our case, could you let me know what I should be looking at to create this list? Apparently this is a manual task: We need to decide a judgement number of each pair ourselves. An ML model will later try to approximate this number based on a number of features which we decide.

Also, there's a learning2rank plugin in ES, which provides basic building blocks. I'm thinking of implementing most of these ourselves (without the plugin), since it shouldn't be a lot of additional work anyway (I think). Thoughts?

**Comment by marco-c** [comment]
> In our case, could you let me know what I should be looking at to create this list? Apparently this is a manual task: We need to decide a judgement number of each pair ourselves. An ML model will later try to approximate this number based on a number of features which we decide.

Maybe we could use the duplicate bug information. In the returned list, the bugs which are duplicate of the queried bug should appear at the top.

> Also, there's a learning2rank plugin in ES, which provides basic building blocks. I'm thinking of implementing most of these ourselves (without the plugin), since it shouldn't be a lot of additional work anyway (I think). Thoughts?

Using the plugin might be better (so we reuse code instead of reimplementing), but I don't know if it supports what we need.

Thinking about this more, maybe what you've recently implemented (applying the duplicate model on top of the similarity results) is already enough (this would be pretty similar to that!), and we just need to evaluate it and improve it.

**Comment by ayush-1506** [comment]
> 
> Thinking about this more, maybe what you've recently implemented (applying the duplicate model on top of the similarity results) is already enough (this would be pretty similar to that!), and we just need to evaluate it and improve it.

@marco-c Yeah, that did cross my mind. If we implement something like learn to rank, it'll finally be yet another xgboost model.

**Comment by suhaibmujahid** [comment]
The duplicate model has been dropped in https://github.com/mozilla/bugbug/pull/3870
