### ISSUE TITLE
Make the models cache an actual cache

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1342]
Right now, it's a simple dict. We preload all models and keep them in memory forever.
We should instead only preload the ones we use often, and unload models from the cache when they haven't been used for a while.

**Comment by marco-c** [comment]
Also, not cache the seldomly requested ones.

**Comment by marco-c** [comment]
So we could do the following:
- cache a model only if it was loaded at least X times in two hours (maybe starting with a low value, like X = 2);
- set a TTL of two hours for cache entries;
- preload only the component model, which is used hourly by relman-auto-nag (and in the future the test selection models).

**Comment by mvkski** [comment]
I'm interested in working on this, and curious as to the motivation for this enhancement. Are there any specific operational issues the service is currently experiencing, or that you foresee it experiencing, if this enhancement is not implemented and the service keeps loading all models into a dict?

**Comment by marco-c** [comment]
> I'm interested in working on this

@mvkski better to start with an issue with the good-first-bug label: https://github.com/mozilla/bugbug/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-bug.
You can still work on this if you want of course, but it might not be as easy as those.
NOTE: The only thing missing here is removing items from the cache after two hours.

> , and curious as to the motivation for this enhancement. Are there any specific operational issues the service is currently experiencing, or that you foresee it experiencing, if this enhancement is not implemented and the service keeps loading all models into a dict?

The reason behind this change is reducing memory usage of the HTTP service. It is currently high, and will be too high if we add more models.

**Comment by mvkski** [comment]
@marco-c Thanks for the suggestion! This issue looked like it might be a good fit for me because the enhancement seems straightforward (if I'm not missing anything) and I am interested in caching technologies, but I may pick up a good-first-bug issue seeing as you recommend doing so. Plan of action for this issue would be something like:

Replace the object at this line of code https://github.com/mozilla/bugbug/blob/22b27b97b0a7ec4d84c8b374cb56c2c5f3f9d734/http_service/bugbug_http/models.py#L41

with a cache that allows the kind of policy you suggest, such as a TTL cache from cachetools (or similar python caching library if cachetools for some reason doesn't work out):
https://github.com/tkem/cachetools/
If using cachetools, we would configured with the 'TTL' parameter specified above set to two hours, and we would make sure that when we get and item, we re-add it to the cache with the same TTL, since by default the TTL does not appear to get updated to be current time + TTL on a get.

For the reason behind this change - To be more specific, I am curious why reducing memory usage of the process is a priority. How big are these models, generally speaking, and how many of them do you expect the project to have? What kind of problems have you seen/do you think you might see due to the high memory usage of the process (process dying? not being able to launch as much software on the machines the service is deployed to due to process size? something else?). I'd really appreciate anything you may have to say on this topic, since it would be a good learning opportunity.

**Comment by mvkski** [comment]
@marco-c Thanks! If you don't mind, I'd like to take a crack at this task for now. I think I have a pretty good handle on what needs to be done here, and have done similar things before.

 If I understand correctly, the following line:
https://github.com/mozilla/bugbug/blob/master/http_service/bugbug_http/models.py#L41
Needs to be switched out from a dict to a cache supporting a TTL. Currently I think https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache with a TTL parameter of two hours would do the trick, but am still researching (not sure if this TTL will refresh when a model is retrieved). 

I had more questions on what problems specifically you might expect to see due to high memory usage, but I think I'll refrain from taking up too much of your time with them at this time (I might feel emboldened to ask if a PR of mine for this issue is accepted 🙂)

**Comment by marco-c** [comment]
>  Needs to be switched out from a dict to a cache supporting a TTL. Currently I think https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache with a TTL parameter of two hours would do the trick, but am still researching (not sure if this TTL will refresh when a model is retrieved).

I've looked at cachetools, but it looks like the cache is only cleaned up when you actually access it, so it doesn't help a lot by itself in reducing memory usage. We could set up a background thread which periodically performs the cleanup.

> I had more questions on what problems specifically you might expect to see due to high memory usage, but I think I'll refrain from taking up too much of your attention with them right now(I might feel emboldened to ask if a PR of mine for this issue is accepted slightly_smiling_face)

Simply: running out of available memory :)
On a Heroku `Standard 2x` worker we only have 1 GB available, so we have to use it carefully.

**Comment by mvkski** [comment]
> I've looked at cachetools, but it looks like the cache is only cleaned up when you actually access it, so it doesn't help a lot by itself in reducing memory usage. We could set up a background thread which periodically performs the cleanup.
 
Thanks for catching that! If we have a cleanup thread run only once every two hours it seems to me like it would solve the problem.  If I understand correctly, the problematic nature of the [global interpreter lock](https://wiki.python.org/moin/GlobalInterpreterLock) applies to this situation, but since the cleanup thread would only need to run very infrequently negative performance effects on inference should be negligible. 
 
> Simply: running out of available memory :)
> On a Heroku `Standard 2x` worker we only have 1 GB available, so we have to use it carefully.

That makes a lot of sense! Thanks - its very satisfying to work on something when you have full visibility into why its needed 😃.

**Comment by marco-c** [comment]
> Thanks for catching that! If we have a cleanup thread run only once every two hours it seems to me like it would solve the problem. If I understand correctly, the problematic nature of the global interpreter lock applies to this situation, but since the cleanup thread would only need to run very infrequently negative performance effects on inference should be negligible.

Indeed!

**Comment by mvkski** [comment]
Also, If we're going to be writing our own cleanup thread, it seems like we may as well go the distance and implement our own TTL cache from scratch rather than take on an external dependancy with more features than we need.

It shouldn't be too much extra code to do so (I'm estimating 20-50 lines?). Having a small amount of extra code in the project seems to me like a fair price to pay for the cost of reducing the chance we end up with [dependancy hell](https://en.wikipedia.org/wiki/Dependency_hell) related problems.

**Comment by marco-c** [comment]
It sounds good to me, we already partially have it now (see https://github.com/mozilla/bugbug/blob/b72e96b269478cdce2b6aceef4beb190238c0eea/http_service/bugbug_http/models.py#L40 and https://github.com/mozilla/bugbug/blob/b72e96b269478cdce2b6aceef4beb190238c0eea/http_service/bugbug_http/models.py#L67-L71), so we just need the cleanup thread to go through the entries and remove stale ones.

**Comment by mvkski** [comment]
Created PR for the issue. Wrote unit tests and an integration test for the cache, but haven't verified end to end yet due to having issues launching http_service locally. Asking in matrix how to launch service.
