### ISSUE TITLE
Figure out what to do with http_service on CI

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#305]
We have two options:
- build the http_service with fake models and don't push it on CI. Build it with real models and push it after training;
- build the http_service without models and let it download models at runtime.

**Comment by Lothiraldan** [comment]
We are currently trying to update the index routes and we hit a chickend-and-egg issue. In order to build a functioning http_service Docker image, we need the models that we download from taskcluster. The issue is that the models are not produced until the data pipeline runs and it runs with the new code only after the release.
