### ISSUE TITLE
Use generic "spawn" image and stop using "spawn-data" and "spawn-check"

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#365]
Follow-up to #341.

**Comment by marco-c** [comment]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1550436.

**Comment by Lothiraldan** [comment]
My main issue with using a generic image only is that the hooks will need to git clone the repository at the right revision in order to be able to spawn the pipelines. This means that if Github is down, the pipelines won't be spawned. We need also to ensure that the `spawn-check` image version X is compatible with hooks in the repository at version Y which not straightforward to do as the hook format is custom at the moment.

**Comment by marco-c** [comment]
We could copy all yml files in the image, so the image contains all it needs to run and we can keep avoiding the git clone and the compatibility problem.

**Comment by Lothiraldan** [comment]
We must create the Docker image `bugbug-spawn` on dockerhub for this issue

**Comment by marco-c** [comment]
bugbug-spawn-pipeline was created in https://bugzilla.mozilla.org/show_bug.cgi?id=1550436, we can use that.
