### ISSUE TITLE
MEI: Store the results of maintenance effectiveness calculations to get a time series

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugbug#3716]
Assuming we calculate the values on a weekly base for the following time intervals:

```
(Yesterday - 1 week, Yesterday)
(Yesterday - 1 month, Yesterday)
(Yesterday - 6 month, Yesterday)
(Yesterday - 12 month, Yesterday)
```

we should store the results to get a time series of evolution.

In order to be able to reconstruct and aggregate the results, we just need to store the basic input values, resulting in a set of:

```
NumOpenedDefects(Component, TimeInterval)
NumClosedDefects(Component, TimeInterval)
NumOpenDefects(Component, End(TimeInterval))
WeighedOpenedDefects(Component, TimeInterval)
WeighedClosedDefects(Component, TimeInterval)
WeighedOpenDefects(Component, End(TimeInterval))
```

Note that this assumes that `Component` is a good minimum granularity. We could segment this further by:

```
ExternalReporter
Fuzzerfound
Intermittent
Other
```

provided that we ensure that the categories do not overlap to be still able to correctly aggregate numbers (each defect must be counted only once for a given time interval and execution time).

**Comment by jensstutte** [comment]
If we want to leave us the possibility to adjust weights or even add new severity levels, instead of storing the weighed numbers we could also just store:

```
NumOpenedDefects(DefectCategory, Component, Severity, TimeInterval)
NumClosedDefects(DefectCategory, Component, Severity, TimeInterval)
NumOpenDefects(DefectCategory, Component, Severity, End(TimeInterval))
```

for each possible/existing value of severity. That would give as the maximum flexibility to use this data as we like.

**Comment by marco-c** [comment]
We have discussed about this on Slack, and we agreed it'd make more sense to calculate it dynamically instead of storing the values.
This is an approximation of course, some bugs will change in severity and component, but we've decided this is a good thing because it reflects reality more (e.g. if a bug was moved from S3 to S2, the WeighedOpenDefects for last year we calculate today is higher than the WeighedOpenDefects we would have calculated last year, but it is a good thing because the actual severity of the bug is S2 and should have likely been S2 since the beginning).
