### ISSUE TITLE
Don't get file_copies from hg log

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#422]
It's pretty slow.
We need it for experience calculation, so we could move this step after the parse patch step.

**Comment by marco-c** [comment]
Probably to be done after #371 to avoid making that harder.

**Comment by calixteman** [comment]
In fact we should move it in _transform and so move xp after _transform.
In order to compute modified files, hg gets some data from the disk and put them in memory.
Since hg export and hg cat need to have almost the same info, if we move file_* stuff in _transform, then all the info for hg things will be there in memory so it should be faster.
And since we're analyzing patch of different sizes in the different processes, it will remove almost all the IO blocking we can see currently (in hg_log)
