### ISSUE TITLE
Use some similarity feature between the summary/first comment of the bugs in the duplicate model

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#582]
E.g. we can use cosine similarity of the bow vectors.

**Comment by ayush-1506** [comment]
@marco-c I have an implementation of using custom transformers to add some cosine similairty information to the features. However, running the model gives me a memoryerror. I tried using a smaller portion of the dataset , but to no avail.
My best guess is that this is happening because in order to add more information to the vectors, I'm converting sparse vectors (Tf-Idf outputs) to dense vectors (to perform other calculations), which is using up a lot of memory.

**Comment by marco-c** [comment]
@ayush-1506 can you submit a PR, so I can help you with that?

**Comment by ayush-1506** [comment]
@marco-c PR created : #616.

**Comment by suhaibmujahid** [comment]
The duplicate model has been dropped in https://github.com/mozilla/bugbug/pull/3870
