### ISSUE TITLE
Show labelled confusion matrix

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#704]
Currently the output is something like:
```
[[ 924   36]
 [  54 1117]]
```
Instead, it would be better to use tabulate to show something like the table on this page: https://en.wikipedia.org/wiki/Confusion_matrix#Example.

**Comment by harsh020** [comment]
@marco-c That would be nice enhancement. I'm a new open source contributor just want to ask few things.
1. Why don't we just create a heatmap instead of tabulating it confusion matrix, as it would be easy to implement as well as more attractive as - 
![Screen Shot 2019-07-16 at 1 15 27 PM](https://user-images.githubusercontent.com/39561084/61275722-2a846f00-a7cc-11e9-9b1d-aad74fa94372.png)

2. If you don't approve of using heatmap, will it be feasible to use PrettyTable library?
3. I'm unable to find where we are evaluating the confusion matrix, can you please tell me.

Thanks.

**Comment by harsh020** [comment]
@marco-c Are you looking for a terminal-integrated output (i.e the output should be displayed only within terminal) or a heatmap will suffice?
![Screen Shot 2019-07-16 at 1 15 27 PM](https://user-images.githubusercontent.com/39561084/61276406-99ae9300-a7cd-11e9-92a7-e7a5c4d18d66.png)

**Comment by marco-c** [comment]
@harsh020 I'd prefer a cli output. It looks like there is already a PR for this (#707), so you could pick up some other good-first-issue.
