### ISSUE TITLE
Use some whiteboard values as labels for the bugtype model

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#720]
E.g. `fxperf` in the whiteboard means that the bug is a performance bug.

**Comment by harsh020** [comment]
Hi @marco-c , I would very much like to work on this issue. 

But don't know why I am unable to set up the repo, I have followed through the contributions but am still unable to set it up? Kindly help me with it.

Thanks.

**Comment by marco-c** [comment]
Hey @harsh020, you'll need to be more specific, otherwise it's going to be impossible for me to help you :)
What problem are you hitting? Please file an issue about it and we'll discuss it there (as it's off-topic for this issue).

**Comment by srimani-programmer** [comment]
Hello, @marco-c  I want to work on this issue. But I didn't understand the issue properly. Can you please explain clearly. I want to work on it to solve the issue.

**Comment by marco-c** [comment]
This issue requires some investigation, maybe it's better if I remove the good-first-issue label.

**Comment by PromiseFru** [comment]
Hello @marco-c, @suhaibmujahid, while investigating this issue, I have a few questions. I'm curious about the occurrence threshold for the values in the whiteboard that are considered "often." I used a threshold of 50 and obtained about 146 values. Additionally, I'm trying to determine the criteria for assigning a bug a specific kind based on the keywords of the bug, as outlined here: 

https://github.com/mozilla/bugbug/blob/0586c6a49732f03781daf43d8726b53e2049e3db/bugbug/models/bugtype.py#L21-L31

I'm unsure about the criteria for assigning a bug a kind, especially since some of the whiteboard values cut across multiple bugs that share several unrelated keywords. I would appreciate some insights on these aspects. 🙏🏾

**Comment by marco-c** [comment]
Perhaps we could start with investigating the top whiteboard tags. Could you share the top 10 tags and one example bug for each?

**Comment by PromiseFru** [comment]
> Perhaps we could start with investigating the top whiteboard tags. Could you share the top 10 tags and one example bug for each?

## Top 10 Whiteboard Tags

| Whiteboard Tags         | Occurrences | Bugs                                                                       | Keywords                           | Type           |
|-------------------------|-------------|---------------------------------------------------------------------------|------------------------------------|----------------|
| wptsync downstream      | 15188       | [1436402](https://bugzilla.mozilla.org/show_bug.cgi?id=1436402) - [wpt-sync] PR 8582 - [css-grid] Add tests for baseline alignment inside auto-sized tracks. |                                    | enhancement    |
| necko-triaged           | 3156        | [650091](https://bugzilla.mozilla.org/show_bug.cgi?id=650091) - Multiple Proxy-Authenticate headers order-dependency bug causes login popup with NTLM + Basic (pick auth schema by safety rating) | ['dev-doc-needed']                | defect         |
| retriggered             | 1516        | [1392106](https://bugzilla.mozilla.org/show_bug.cgi?id=1392106) - Intermittent letter missing in reftests on Windows 7 | ['intermittent-failure']           | defect         |
| wpt                     | 1178        | [1626108](https://bugzilla.mozilla.org/show_bug.cgi?id=1626108) - New wpt failures from PR 22547 in /css/css-flexbox/negative-overflow.html |                                    | defect         |
| fxdroid                 | 992         | [1796319](https://bugzilla.mozilla.org/show_bug.cgi?id=1796319) - Add-on settings opened in a new tab every time |                                    | defect         |
| gfx-noted               | 985         | [1112606](https://bugzilla.mozilla.org/show_bug.cgi?id=1112606) - Use the new SyncObject infrastructure for syncing D3D11 ANGLE textures instead of IDXGIKeyedMutex |                                    | enhancement    |
| bugmon:bisected,confirmed| 958         | [1612928](https://bugzilla.mozilla.org/show_bug.cgi?id=1612928) - Assertion failure: !mSyncLoopTarget, at /builds/worker/workspace/build/src/dom/xhr/XMLHttpRequestWorker.cpp:839 | ['assertion', 'testcase']         | defect         |
| addons-jira             | 955         | [1437171](https://bugzilla.mozilla.org/show_bug.cgi?id=1437171) - Implement Permission API updates for WebMIDI | ['dev-doc-complete']               | enhancement    |
| stockwell unknown       | 916         | [1203438](https://bugzilla.mozilla.org/show_bug.cgi?id=1203438) - Intermittent test_trackingprotection_whitelist.html | ['intermittent-failure']           | defect         |
| post-critsmash-triage   | 693         | [1145314](https://bugzilla.mozilla.org/show_bug.cgi?id=1145314) - Lock down the URI_IS_UI_RESOURCE bits of CheckLoadURI some more | ['sec-other']                     | defect         |

**Comment by marco-c** [comment]
I don't see anything interesting in these top 10. Maybe let's list all of the 146 in a shared doc somewhere, and we can all look at them.

As columns, use the ones from the table above but leave the column "Type" empty and we fill it with our idea for a bug type.

**Comment by PromiseFru** [comment]
> I don't see anything interesting in these top 10. Maybe let's list all of the 146 in a shared doc somewhere, and we can all look at them.
> 
> As columns, use the ones from the table above but leave the column "Type" empty and we fill it with our idea for a bug type.

Here is a link to a Google Sheets document containing 145 whiteboard tags: https://docs.google.com/spreadsheets/d/1WTKFOk0i-gTFV5cYAUJoxh3Dio0KwMC_p0Fpk7E2Oh4/edit?usp=sharing.

**Comment by PromiseFru** [comment]
@marco-c was wondering, would it be useful to add more example bug IDs per whiteboard value? Perhaps it can make identifying patterns easier.

**Comment by suhaibmujahid** [comment]
> was wondering, would it be useful to add more example bug IDs per whiteboard value? Perhaps it can make identifying patterns easier.

@PromiseFru I added a link for each of the tags to query all occurrences.

**Comment by PromiseFru** [comment]
> > was wondering, would it be useful to add more example bug IDs per whiteboard value? Perhaps it can make identifying patterns easier.
> 
> @PromiseFru I added a link for each of the tags to query all occurrences.

Great solution, @suhaibmujahid! Thank you 🙏🏾

**Comment by marco-c** [comment]
I did an initial pass, there are only a few left to check.

**Comment by marco-c** [comment]
I have filled the rest.
