### ISSUE TITLE
Figure out how to consider new bugs that don't belong to the pre-existing corpus

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#871]
We will train the similarity model once a week (or once every two weeks), but new bugs are filed every day and we need to find duplicates between those bugs too (actually, especially between those bugs).

**Comment by ayush-1506** [comment]
One way could be to refresh the db every time we try to run a similarity model. Else, we could get a list of all bugs not in db that have been registered before the test bug was added (bugs registered in the past week, for instance) and add these to the list. (Although this will be slow since we'd have to make multiple requests.)

**Comment by marco-c** [comment]
Could you do a quick test with the current DB (train a model on the current corpus except the last 1000 bugs, then try to add the last 1000 bugs and do a query on all bugs)

**Comment by suhaibmujahid** [comment]
The similarity model has been dropped in https://github.com/mozilla/bugbug/pull/3870
